export type MenuCategory = {
  slug: string;
  name: { ro: string; en: string };
  description?: { ro: string; en: string };
  order: number;
};

export type MenuItem = {
  id: string;
  categorySlug: string;
  name: { ro: string; en: string };
  description: { ro: string; en: string };
  price: number;
  isSignature?: boolean;
  isPopular?: boolean;
};

export type Testimonial = {
  id: string;
  name: string;
  role: { ro: string; en: string };
  quote: { ro: string; en: string };
  rating: number;
  createdAt?: Date;
};

export const menuCategories: MenuCategory[] = [
  {
    slug: "cele-mai-comandate",
    name: { ro: "Cele mai comandate", en: "Most Ordered" },
    description: { ro: "Preferatele oaspeților noștri, perfecte pentru prima vizită.", en: "Our guests' favorites, perfect for a first visit." },
    order: 1,
  },
  {
    slug: "salate",
    name: { ro: "Salate", en: "Salads" },
    description: { ro: "Prospețime vibrantă, ușor condimentată.", en: "Vibrant freshness, lightly seasoned." },
    order: 2,
  },
  {
    slug: "mezze-reci",
    name: { ro: "Gustări reci", en: "Cold Appetizers" },
    description: { ro: "Mezze clasice cu texturi cremoase și crocante.", en: "Classic mezze with creamy and crunchy textures." },
    order: 3,
  },
  {
    slug: "mezze-calde",
    name: { ro: "Gustări calde", en: "Hot Appetizers" },
    description: { ro: "Arome bogate, gătite lent, servite fierbinte.", en: "Rich flavors, slow-cooked, served hot." },
    order: 4,
  },
  {
    slug: "carne-cruda",
    name: { ro: "Carne crudă", en: "Raw Meat" },
    description: { ro: "Specialități tartar și kibbeh nayeh.", en: "Tartar specialties and kibbeh nayeh." },
    order: 5,
  },
  {
    slug: "gratar",
    name: { ro: "Grătar", en: "Grill" },
    description: { ro: "Carne fragedă, marinată după rețete libaneze.", en: "Tender meat, marinated with Lebanese recipes." },
    order: 6,
  },
  {
    slug: "peste-fructe-de-mare",
    name: { ro: "Pește și fructe de mare", en: "Fish & Seafood" },
    description: { ro: "Preparat pe jar cu ierburi orientale.", en: "Charcoal-grilled with oriental herbs." },
    order: 7,
  },
  {
    slug: "garnituri",
    name: { ro: "Garnituri", en: "Side Dishes" },
    description: { ro: "Împărțite sau adăugate la felurile principale.", en: "Shared or added to main courses." },
    order: 8,
  },
  {
    slug: "desert",
    name: { ro: "Deserturi", en: "Desserts" },
    description: { ro: "Final dulce, parfum de fistic și apă de trandafiri.", en: "Sweet ending, pistachio and rose water aroma." },
    order: 9,
  },
];

export const menuItems: MenuItem[] = [
  {
    id: "green-salad",
    categorySlug: "salate",
    name: { ro: "Salată verde", en: "Green Salad" },
    description: { ro: "Salată cos, sare, lămâie și ulei de măsline", en: "Cos lettuce, salt, lemon and olive oil" },
    price: 41,
  },
  {
    id: "coconut-sorbet",
    categorySlug: "desert",
    name: { ro: "Sorbet de cocos", en: "Coconut Sorbet" },
    description: { ro: "Sorbet răcoritor de cocos", en: "Refreshing coconut sorbet" },
    price: 57,
  },
  {
    id: "assorted-ice-cream",
    categorySlug: "desert",
    name: { ro: "Înghețată asortată", en: "Assorted Ice Cream" },
    description: { ro: "Selecție de înghețată artizanală", en: "Selection of artisan ice cream" },
    price: 62,
  },
  {
    id: "baklava-with-ice-cream",
    categorySlug: "desert",
    name: { ro: "Baklava cu înghețată", en: "Baklava with Ice Cream" },
    description: { ro: "Baklava tradițională servită cu înghețată de vanilie", en: "Traditional baklava served with vanilla ice cream" },
    price: 93,
  },
  {
    id: "zaitoone-cake",
    categorySlug: "desert",
    name: { ro: "Tort cu rodie", en: "Pomegranate Cake" },
    description: { ro: "Tort delicat cu aromă de rodie", en: "Delicate cake with pomegranate flavor" },
    price: 57,
  },
  {
    id: "dubai-chocolate",
    categorySlug: "desert",
    name: { ro: "Ciocolată Dubai", en: "Dubai Chocolate" },
    description: { ro: "Ciocolată cu cremă de fistic și frișcă", en: "Chocolate with pistachio cream and whipped cream" },
    price: 57,
  },
  {
    id: "chocolate-souffle-with-ice-cream",
    categorySlug: "desert",
    name: { ro: "Sufleu de ciocolată cu înghețată", en: "Chocolate Soufflé with Ice Cream" },
    description: { ro: "Sufleu cald de ciocolată servit cu înghețată", en: "Warm chocolate soufflé served with ice cream" },
    price: 57,
  },
  {
    id: "desertul-casei",
    categorySlug: "desert",
    name: { ro: "Desertul casei", en: "House Special Dessert" },
    description: { ro: "Cremă de lapte învelită într-o crustă de migdale și dulceață de smochine", en: "Milk cream wrapped in an almond crust with fig jam" },
    price: 57,
  },
  {
    id: "osmalie",
    categorySlug: "desert",
    name: { ro: "Osmalie", en: "Osmalie" },
    description: { ro: "Fidea, cremă de lapte, miere și fistic", en: "Vermicelli, milk cream, honey and pistachio" },
    price: 57,
  },
  {
    id: "kunefe-la-shish",
    categorySlug: "desert",
    name: { ro: "Künefe la frigare", en: "Kunefe on Skewer" },
    description: { ro: "Fidea caramelizată, brânză dulce, miere și fistic", en: "Caramelized vermicelli, sweet cheese, honey and pistachio" },
    price: 155,
  },
  {
    id: "kunefe",
    categorySlug: "desert",
    name: { ro: "Künefe", en: "Kunefe" },
    description: { ro: "Brânză dulce și fidea, miere și fistic", en: "Sweet cheese and vermicelli, honey and pistachio" },
    price: 57,
  },
  {
    id: "katayef-with-nuts",
    categorySlug: "desert",
    name: { ro: "Katayef cu nuci", en: "Katayef with Nuts" },
    description: { ro: "Aluat umplut cu nuci", en: "Dough filled with nuts" },
    price: 57,
  },
  {
    id: "katayef-with-cheese",
    categorySlug: "desert",
    name: { ro: "Katayef cu brânză", en: "Katayef with Cheese" },
    description: { ro: "Aluat umplut cu brânză dulce", en: "Dough filled with sweet cheese" },
    price: 57,
  },
  {
    id: "kilimanjaro",
    categorySlug: "desert",
    name: { ro: "Kilimanjaro", en: "Kilimanjaro" },
    description: { ro: "Cremă de lapte, mousse, înghețată de vanilie, miere și fistic", en: "Milk cream, mousse, vanilla ice cream, honey and pistachio" },
    price: 67,
  },
  {
    id: "baclava",
    categorySlug: "desert",
    name: { ro: "Baclava", en: "Baklava" },
    description: { ro: "Foi crocante cu nuci, caju și sirop", en: "Crispy layers with walnuts, cashews and syrup" },
    price: 57,
  },
  {
    id: "fruits-salad",
    categorySlug: "desert",
    name: { ro: "Salată de fructe", en: "Fruit Salad" },
    description: { ro: "Afine, căpșuni, kiwi, ananas, pepene și suc de portocale", en: "Blueberry, strawberry, kiwi, pineapple, melon and orange juice" },
    price: 57,
  },
  {
    id: "ashta",
    categorySlug: "desert",
    name: { ro: "Ashta", en: "Ashta" },
    description: { ro: "Cremă de lapte, felii de banană, miere și fistic", en: "Milk cream, banana slices, honey and pistachio" },
    price: 57,
  },
  {
    id: "rice-with-chicken-almonds-and-pine-buds",
    categorySlug: "garnituri",
    name: { ro: "Orez cu pui, migdale și muguri de pin", en: "Rice with Chicken, Almonds and Pine Nuts" },
    description: { ro: "Orez aromat cu bucăți de pui, migdale și muguri de pin", en: "Aromatic rice with chicken pieces, almonds and pine nuts" },
    price: 36,
  },
  {
    id: "rice-with-meat-almonds-and-raisins",
    categorySlug: "garnituri",
    name: { ro: "Orez cu carne, migdale și stafide", en: "Rice with Meat, Almonds and Raisins" },
    description: { ro: "Orez parfumat cu carne tocată, migdale și stafide", en: "Fragrant rice with minced meat, almonds and raisins" },
    price: 36,
  },
  {
    id: "basmati-rice-with-vegetables",
    categorySlug: "garnituri",
    name: { ro: "Orez basmati cu legume", en: "Basmati Rice with Vegetables" },
    description: { ro: "Orez basmati cu legume proaspete", en: "Basmati rice with fresh vegetables" },
    price: 29,
  },
  {
    id: "basmati-rice-with-noodles",
    categorySlug: "garnituri",
    name: { ro: "Orez basmati cu fidea", en: "Basmati Rice with Noodles" },
    description: { ro: "Orez basmati tradițional cu fidea prăjită", en: "Traditional basmati rice with fried vermicelli" },
    price: 29,
  },
  {
    id: "plain-boiled-basmati-rice",
    categorySlug: "garnituri",
    name: { ro: "Orez basmati fiert", en: "Plain Boiled Basmati Rice" },
    description: { ro: "Orez basmati simplu, fiert la perfecție", en: "Simple basmati rice, perfectly boiled" },
    price: 29,
  },
  {
    id: "mashed-potatoes-with-truffles",
    categorySlug: "garnituri",
    name: { ro: "Piure de cartofi cu trufe", en: "Mashed Potatoes with Truffles" },
    description: { ro: "Piure cremos de cartofi cu trufe negre", en: "Creamy mashed potatoes with black truffles" },
    price: 40,
  },
  {
    id: "mashed-potatoes",
    categorySlug: "garnituri",
    name: { ro: "Piure de cartofi", en: "Mashed Potatoes" },
    description: { ro: "Piure cremos de cartofi cu unt", en: "Creamy mashed potatoes with butter" },
    price: 26,
  },
  {
    id: "fries-with-mint-and-garlic",
    categorySlug: "garnituri",
    name: { ro: "Cartofi prăjiți cu mentă și usturoi", en: "Fries with Mint and Garlic" },
    description: { ro: "Cartofi prăjiți condimentați cu mentă și usturoi", en: "Fries seasoned with mint and garlic" },
    price: 27,
  },
  {
    id: "french-fries",
    categorySlug: "garnituri",
    name: { ro: "Cartofi prăjiți", en: "French Fries" },
    description: { ro: "Cartofi prăjiți crocanți", en: "Crispy french fries" },
    price: 26,
  },
  {
    id: "thin-potato-chips",
    categorySlug: "garnituri",
    name: { ro: "Chipsuri de cartofi", en: "Thin Potato Chips" },
    description: { ro: "Chipsuri subțiri și crocante de cartofi", en: "Thin and crispy potato chips" },
    price: 50,
  },
  {
    id: "octopus-skewers",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Frigărui de caracatiță", en: "Octopus Skewers" },
    description: { ro: "Caracatiță la grătar pe frigărui", en: "Grilled octopus on skewers" },
    price: 190,
  },
  {
    id: "octopus-with-curry-sauce-and-rice",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Caracatiță cu sos curry și orez", en: "Octopus with Curry Sauce and Rice" },
    description: { ro: "Caracatiță fragedă cu sos curry și orez basmati", en: "Tender octopus with curry sauce and basmati rice" },
    price: 210,
  },
  {
    id: "marinated-octopus",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Caracatiță marinată", en: "Marinated Octopus" },
    description: { ro: "Caracatiță marinată cu ierburi și ulei de măsline", en: "Octopus marinated with herbs and olive oil" },
    price: 185,
  },
  {
    id: "breaded-squid-with-french-fries",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Calamari pane cu cartofi prăjiți", en: "Breaded Squid with French Fries" },
    description: { ro: "Inele de calamari în crustă crocantă cu cartofi prăjiți", en: "Crispy breaded squid rings with french fries" },
    price: 103,
  },
  {
    id: "grilled-baby-calamari-with-feta",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Calamari baby la grătar cu feta", en: "Grilled Baby Calamari with Feta" },
    description: { ro: "Calamari mici la grătar cu brânză feta", en: "Small grilled calamari with feta cheese" },
    price: 160,
  },
  {
    id: "squid-with-lemon-sauce",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Calamari cu sos de lămâie", en: "Squid with Lemon Sauce" },
    description: { ro: "Calamari fragezi cu sos proaspăt de lămâie", en: "Tender squid with fresh lemon sauce" },
    price: 93,
  },
  {
    id: "shawarma-with-fish",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Shawarma cu pește", en: "Fish Shawarma" },
    description: { ro: "Pește marinat în stil shawarma", en: "Fish marinated shawarma style" },
    price: 130,
  },
  {
    id: "grilled-seafood-mix-with-roca-salad",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Mix de fructe de mare la grătar cu salată de rucola", en: "Grilled Seafood Mix with Arugula Salad" },
    description: { ro: "Selecție de fructe de mare la grătar cu salată de rucola", en: "Selection of grilled seafood with arugula salad" },
    price: 180,
  },
  {
    id: "zaitoone-shrimp-with-pomegranate-sauce",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Creveți Zaitoone cu sos de rodie", en: "Zaitoone Shrimp with Pomegranate Sauce" },
    description: { ro: "Creveți aromați cu sos special de rodie", en: "Aromatic shrimp with special pomegranate sauce" },
    price: 67,
    isSignature: true,
  },
  {
    id: "breaded-shrimp-and-fries",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Creveți pane cu cartofi prăjiți", en: "Breaded Shrimp with Fries" },
    description: { ro: "Creveți în crustă crocantă cu cartofi prăjiți", en: "Crispy breaded shrimp with french fries" },
    price: 87,
  },
  {
    id: "shrimp-with-hot-white-sauce",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Creveți cu sos alb picant", en: "Shrimp with Hot White Sauce" },
    description: { ro: "Creveți în sos alb cremos și picant", en: "Shrimp in creamy and spicy white sauce" },
    price: 70,
  },
  {
    id: "wild-sea-wolf",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Lup de mare sălbatic", en: "Wild Sea Bass" },
    description: { ro: "Lup de mare sălbatic la grătar", en: "Wild grilled sea bass" },
    price: 640,
  },
  {
    id: "sea-wolf",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Lup de mare", en: "Sea Bass" },
    description: { ro: "Lup de mare la grătar", en: "Grilled sea bass" },
    price: 154,
  },
  {
    id: "wagyu-beef-entrecote",
    categorySlug: "gratar",
    name: { ro: "Antricot de vită Wagyu", en: "Wagyu Beef Entrecote" },
    description: { ro: "Antricot premium de vită Wagyu", en: "Premium Wagyu beef entrecote" },
    price: 255,
  },
  {
    id: "assorted-grilled-vegetables",
    categorySlug: "gratar",
    name: { ro: "Legume la grătar asortate", en: "Assorted Grilled Vegetables" },
    description: { ro: "Selecție de legume proaspete la grătar", en: "Selection of fresh grilled vegetables" },
    price: 72,
  },
  {
    id: "arayes-halloumi",
    categorySlug: "gratar",
    name: { ro: "Arayes Halloumi", en: "Arayes Halloumi" },
    description: { ro: "Lipie libaneză cu halloumi și mentă", en: "Lebanese pita with halloumi and mint" },
    price: 62,
  },
  {
    id: "arayes-chicken-and-cheese",
    categorySlug: "gratar",
    name: { ro: "Arayes cu pui și brânză", en: "Arayes Chicken and Cheese" },
    description: { ro: "Lipie libaneză cu pui și brânză", en: "Lebanese pita with chicken and cheese" },
    price: 62,
  },
  {
    id: "arayes-kafta-special",
    categorySlug: "gratar",
    name: { ro: "Arayes Kafta Special", en: "Arayes Kafta Special" },
    description: { ro: "Lipie libaneză cu carne tocată", en: "Lebanese pita with minced meat" },
    price: 77,
  },
  {
    id: "arayes-kafta",
    categorySlug: "gratar",
    name: { ro: "Arayes Kafta", en: "Arayes Kafta" },
    description: { ro: "Lipie libaneză cu carne tocată și brânză", en: "Lebanese pita with minced meat and cheese" },
    price: 72,
  },
  {
    id: "arayes-cheese",
    categorySlug: "gratar",
    name: { ro: "Arayes cu brânză", en: "Arayes Cheese" },
    description: { ro: "Lipie libaneză cu brânză", en: "Lebanese pita with cheese" },
    price: 57,
  },
  {
    id: "mixed-grill",
    categorySlug: "gratar",
    name: { ro: "Grătar mixt", en: "Mixed Grill" },
    description: { ro: "Cuburi de mușchi de vită, pui, kafta, cartofi prăjiți și cotlet de miel", en: "Cubes of beef tenderloin, chicken, kafta, fries and lamb chop" },
    price: 180,
  },
  {
    id: "grilled-lamb-pastrami",
    categorySlug: "gratar",
    name: { ro: "Pastramă de miel la grătar", en: "Grilled Lamb Pastrami" },
    description: { ro: "Pastramă de miel la grătar cu condimente", en: "Grilled lamb pastrami with spices" },
    price: 123,
  },
  {
    id: "lamb-chop",
    categorySlug: "gratar",
    name: { ro: "Cotlet de miel", en: "Lamb Chop" },
    description: { ro: "Cotlet de miel la grătar cu cartofi prăjiți", en: "Grilled lamb chop with french fries" },
    price: 165,
  },
  {
    id: "ram-skewers",
    categorySlug: "gratar",
    name: { ro: "Frigărui de berbec", en: "Lamb Skewers" },
    description: { ro: "Mușchi de berbec la grătar cu cartofi prăjiți", en: "Grilled lamb loin with french fries" },
    price: 118,
  },
  {
    id: "beef-skewers",
    categorySlug: "gratar",
    name: { ro: "Frigărui de vită", en: "Beef Skewers" },
    description: { ro: "Mușchi de vită la grătar cu cartofi prăjiți", en: "Grilled beef tenderloin with french fries" },
    price: 124,
    isSignature: true,
  },
  {
    id: "chicken-cutlets",
    categorySlug: "gratar",
    name: { ro: "Șnițel de pui", en: "Chicken Cutlets" },
    description: { ro: "Aripi de pui dezosate, usturoi, salată coleslaw și cartofi prăjiți", en: "Boneless chicken wings, garlic, coleslaw and french fries" },
    price: 102,
  },
  {
    id: "chicken-skewers",
    categorySlug: "gratar",
    name: { ro: "Frigărui de pui", en: "Chicken Skewers" },
    description: { ro: "Cuburi de piept de pui marinate în sos de usturoi cu cartofi prăjiți", en: "Chicken breast cubes marinated in garlic sauce with french fries" },
    price: 113,
  },
  {
    id: "chicken-breast",
    categorySlug: "gratar",
    name: { ro: "Piept de pui", en: "Chicken Breast" },
    description: { ro: "Piept de pui marinat la grătar cu cartofi prăjiți", en: "Grilled marinated chicken breast with french fries" },
    price: 102,
  },
  {
    id: "chicken-wings",
    categorySlug: "gratar",
    name: { ro: "Aripi de pui", en: "Chicken Wings" },
    description: { ro: "Aripi de pui marinate la grătar cu cartofi prăjiți", en: "Grilled marinated chicken wings with fries" },
    price: 102,
  },
  {
    id: "kebab-orfali",
    categorySlug: "gratar",
    name: { ro: "Kebab Orfali", en: "Kebab Orfali" },
    description: { ro: "Carne tocată de vită și miel cu sos de roșii picant", en: "Minced beef and lamb with spicy tomato sauce" },
    price: 118,
  },
  {
    id: "olive-kebab",
    categorySlug: "gratar",
    name: { ro: "Kebab cu măsline", en: "Olive Kebab" },
    description: { ro: "Carne tocată de vită și miel cu ceapă și busuioc", en: "Minced beef and lamb with onion and basil" },
    price: 118,
  },
  {
    id: "kebab-with-lard",
    categorySlug: "gratar",
    name: { ro: "Kebab cu iaurt", en: "Kebab with Yogurt" },
    description: { ro: "Carne tocată de vită și miel cu iaurt", en: "Minced beef and lamb with yogurt" },
    price: 118,
  },
  {
    id: "kebab",
    categorySlug: "gratar",
    name: { ro: "Kafta", en: "Kafta" },
    description: { ro: "Carne tocată de vită și miel cu usturoi în lipie", en: "Minced beef and lamb with garlic in pita bread" },
    price: 124,
  },
  {
    id: "adana-kebab",
    categorySlug: "gratar",
    name: { ro: "Kebab Adana", en: "Adana Kebab" },
    description: { ro: "Carne tocată de vită și miel cu usturoi și ardei iute", en: "Minced beef and lamb with garlic and paprika" },
    price: 118,
  },
  {
    id: "basturma",
    categorySlug: "carne-cruda",
    name: { ro: "Pastramă", en: "Basturma" },
    description: { ro: "Mușchi de vită uscat cu condimente speciale", en: "Dried beef tenderloin with special spices" },
    price: 49,
  },
  {
    id: "frake",
    categorySlug: "carne-cruda",
    name: { ro: "Frake", en: "Frake" },
    description: { ro: "Bulgur, mușchi de miel, pastă picantă, ceapă, mentă", en: "Bulgur, lamb loin, spicy paste, onion, mint" },
    price: 72,
  },
  {
    id: "lipie-zaitoone",
    categorySlug: "mezze-calde",
    name: { ro: "Lipie Zaitoone", en: "Zaitoone Bread" },
    description: { ro: "Pâine caldă proaspăt scoasă din cuptor", en: "Hot bread fresh from the oven" },
    price: 15,
    isSignature: true,
  },
  {
    id: "sfiha-(6-pieces)",
    categorySlug: "mezze-calde",
    name: { ro: "Sfiha (6 bucăți)", en: "Sfiha (6 pieces)" },
    description: { ro: "Plăcintele libaneze cu carne de vită și miel", en: "Lebanese meat pies with beef and lamb" },
    price: 41,
  },
  {
    id: "lahm-be-ajiin",
    categorySlug: "mezze-calde",
    name: { ro: "Lahm Be Ajiin", en: "Lahm Be Ajiin" },
    description: { ro: "Aluat cu carne tocată, ceapă și roșii", en: "Dough with minced meat, onion and tomatoes" },
    price: 52,
  },
  {
    id: "manakish-jibneh",
    categorySlug: "mezze-calde",
    name: { ro: "Manakish Jibneh", en: "Manakish Jibneh" },
    description: { ro: "Aluat cu trei tipuri de brânză", en: "Dough with three types of cheese" },
    price: 41,
  },
  {
    id: "manakish-zaatar",
    categorySlug: "mezze-calde",
    name: { ro: "Manakish Zaatar", en: "Manakish Zaatar" },
    description: { ro: "Aluat cu cimbru și ulei de măsline", en: "Dough with thyme and olive oil" },
    price: 36,
  },
  {
    id: "fatteh-with-spicy-potatoes",
    categorySlug: "mezze-calde",
    name: { ro: "Fatteh cu cartofi picanți", en: "Fatteh with Spicy Potatoes" },
    description: { ro: "Vinete, cartofi picanți, vită și sos roșu", en: "Eggplant, chili potatoes, beef and red sauce" },
    price: 60,
  },
  {
    id: "eggplant-fatteh",
    categorySlug: "mezze-calde",
    name: { ro: "Fatteh cu vinete", en: "Eggplant Fatteh" },
    description: { ro: "Vinete, pâine prăjită, vită și sos roșu", en: "Eggplant, toasted bread, beef and red sauce" },
    price: 60,
  },
  {
    id: "shrimp-fatteh",
    categorySlug: "mezze-calde",
    name: { ro: "Fatteh cu creveți", en: "Shrimp Fatteh" },
    description: { ro: "Creveți, coriandru, usturoi, boia, ulei de măsline, iaurt, năut și muguri de pin", en: "Shrimp, coriander, garlic, paprika, olive oil, yogurt, chickpeas and pine nuts" },
    price: 72,
  },
  {
    id: "fatteh-with-chicken-and-rice",
    categorySlug: "mezze-calde",
    name: { ro: "Fatteh cu pui și orez", en: "Fatteh with Chicken and Rice" },
    description: { ro: "Pui, orez și sumac", en: "Chicken, rice and sumac" },
    price: 60,
  },
  {
    id: "fatteh-with-spinach-rice-and-beef",
    categorySlug: "mezze-calde",
    name: { ro: "Fatteh cu spanac, orez și vită", en: "Fatteh with Spinach, Rice and Beef" },
    description: { ro: "Spanac, orez, vită, muguri de pin și iaurt", en: "Spinach, rice, beef, pine nuts and yogurt" },
    price: 67,
  },
  {
    id: "fatteh-humous-with-meat-and-pine-buds",
    categorySlug: "mezze-calde",
    name: { ro: "Fatteh Hummus cu carne și muguri de pin", en: "Fatteh Hummus with Meat and Pine Nuts" },
    description: { ro: "Vită cu năut, usturoi, iaurt, pâine prăjită și muguri de pin", en: "Beef with chickpeas, garlic, yogurt, toast and pine nuts" },
    price: 67,
  },
  {
    id: "simple-fatteh",
    categorySlug: "mezze-calde",
    name: { ro: "Fatteh simplu", en: "Simple Fatteh" },
    description: { ro: "Năut, tahini, usturoi, iaurt, lipie prăjită și muguri de pin", en: "Chickpeas, tahini, garlic, yogurt, fried pita bread and pine nuts" },
    price: 57,
  },
  {
    id: "crispy-olive-chicken",
    categorySlug: "mezze-calde",
    name: { ro: "Pui Zaitoone crocant", en: "Crispy Zaitoone Chicken" },
    description: { ro: "Piept de pui pane cu sos Provensale", en: "Breaded chicken breast with Provensale sauce" },
    price: 55,
  },
  {
    id: "chicken-ras-asfour",
    categorySlug: "mezze-calde",
    name: { ro: "Ras Asfour de pui", en: "Chicken Ras Asfour" },
    description: { ro: "Cuburi de piept de pui cu ceapă, ardei și sos de rodie", en: "Diced chicken breast with onion, bell pepper and pomegranate sauce" },
    price: 55,
  },
  {
    id: "ras-asfour-vita-zaitoone",
    categorySlug: "mezze-calde",
    name: { ro: "Ras Asfour Vită Zaitoone", en: "Ras Asfour Beef Zaitoone" },
    description: { ro: "Cuburi de mușchi de vită, muguri de pin, usturoi, busuioc și parmezan", en: "Diced beef tenderloin, pine nuts, garlic, basil and parmesan" },
    price: 67,
  },
  {
    id: "beef-ras-asfour",
    categorySlug: "mezze-calde",
    name: { ro: "Ras Asfour de vită", en: "Beef Ras Asfour" },
    description: { ro: "Cuburi de mușchi de vită cu ceapă și sos de rodie", en: "Diced beef tenderloin with onion and pomegranate sauce" },
    price: 67,
  },
  {
    id: "aries-ras-asfour-(hot)",
    categorySlug: "mezze-calde",
    name: { ro: "Ras Asfour de miel (picant)", en: "Lamb Ras Asfour (Hot)" },
    description: { ro: "Cuburi de mușchi de miel, ulei de măsline, muguri de pin, usturoi și ardei iute", en: "Diced lamb loin, olive oil, pine nuts, garlic and chili pepper" },
    price: 77,
  },
  {
    id: "beef-sharhat-by-zaitoone",
    categorySlug: "mezze-calde",
    name: { ro: "Sharhat de vită Zaitoone", en: "Beef Zaitoone Sharhat" },
    description: { ro: "Felii de mușchi de vită cu sos alb", en: "Sliced beef tenderloin with white sauce" },
    price: 67,
  },
  {
    id: "sharhat-de-vita",
    categorySlug: "mezze-calde",
    name: { ro: "Sharhat de vită cu sos de rodie", en: "Beef Sharhat with Pomegranate Sauce" },
    description: { ro: "Felii de mușchi de vită cu sos special de rodie", en: "Sliced beef tenderloin with special pomegranate sauce" },
    price: 80,
  },
  {
    id: "zaitoone-chicken-sharhat",
    categorySlug: "mezze-calde",
    name: { ro: "Sharhat de pui Zaitoone", en: "Zaitoone Chicken Sharhat" },
    description: { ro: "Piept de pui, usturoi, ardei verde iute și smântână", en: "Chicken breast, garlic, green chili pepper and sour cream" },
    price: 55,
    isSignature: true,
  },
  {
    id: "chicken-sharhat",
    categorySlug: "mezze-calde",
    name: { ro: "Sharhat de pui", en: "Chicken Sharhat" },
    description: { ro: "Felii de piept de pui cu sos de lămâie", en: "Sliced chicken breast with lemon sauce" },
    price: 50,
  },
  {
    id: "beef-shawarma",
    categorySlug: "mezze-calde",
    name: { ro: "Shawarma de vită", en: "Beef Shawarma" },
    description: { ro: "Mușchi de vită marinat în sos special", en: "Beef marinated in special sauce" },
    price: 82,
  },
  {
    id: "chicken-shawarma",
    categorySlug: "mezze-calde",
    name: { ro: "Shawarma de pui", en: "Chicken Shawarma" },
    description: { ro: "Piept de pui marinat în sos special", en: "Chicken breast marinated in special sauce" },
    price: 72,
  },
  {
    id: "chicken-liver",
    categorySlug: "mezze-calde",
    name: { ro: "Ficat de pui", en: "Chicken Liver" },
    description: { ro: "Ficat de pui cu usturoi și sos de rodie", en: "Chicken liver with garlic and pomegranate sauce" },
    price: 54,
  },
  {
    id: "sujuk",
    categorySlug: "mezze-calde",
    name: { ro: "Sucuk", en: "Sujuk" },
    description: { ro: "Cârnați picanți cu roșii și usturoi sau sos de rodie", en: "Spicy sausages with tomatoes and garlic or pomegranate sauce" },
    price: 57,
  },
  {
    id: "makanek",
    categorySlug: "mezze-calde",
    name: { ro: "Makanek", en: "Makanek" },
    description: { ro: "Cârnați cu sos de rodie și lămâie", en: "Sausages with pomegranate and lemon sauce" },
    price: 57,
  },
  {
    id: "falafel",
    categorySlug: "mezze-calde",
    name: { ro: "Falafel", en: "Falafel" },
    description: { ro: "Chifteluțe de năut cu ceapă, coriandru și usturoi", en: "Chickpea fritters with onion, coriander and garlic" },
    price: 49,
  },
  {
    id: "tongue",
    categorySlug: "mezze-calde",
    name: { ro: "Limbă", en: "Tongue" },
    description: { ro: "Limbă cu usturoi și sos de lămâie", en: "Tongue with garlic and lemon sauce" },
    price: 62,
  },
  {
    id: "aries-brain-(wedge)",
    categorySlug: "mezze-calde",
    name: { ro: "Creier de berbec pane", en: "Breaded Lamb Brain" },
    description: { ro: "Creier de berbec pane cu sos de lămâie", en: "Breaded lamb brain with lemon sauce" },
    price: 67,
  },
  {
    id: "aries-brain",
    categorySlug: "mezze-calde",
    name: { ro: "Creier de berbec", en: "Lamb Brain" },
    description: { ro: "Creier cu sos de lămâie și coriandru", en: "Brain with lemon and coriander sauce" },
    price: 60,
  },
  {
    id: "batata-harra-sweet-potato-hot-potatoes",
    categorySlug: "mezze-calde",
    name: { ro: "Batata Harra", en: "Batata Harra" },
    description: { ro: "Cuburi de cartofi prăjiți cu coriandru, usturoi și pastă de ardei iute", en: "Diced fries with coriander, garlic and chili paste" },
    price: 38,
  },
  {
    id: "halloumi-with-almonds",
    categorySlug: "mezze-calde",
    name: { ro: "Halloumi cu migdale", en: "Halloumi with Almonds" },
    description: { ro: "Brânză halloumi, migdale și dulceață de smochine", en: "Halloumi cheese, almonds and fig jam" },
    price: 66,
  },
  {
    id: "halloumi-cheese",
    categorySlug: "mezze-calde",
    name: { ro: "Brânză halloumi", en: "Halloumi Cheese" },
    description: { ro: "Brânză halloumi la grătar", en: "Grilled halloumi cheese" },
    price: 49,
  },
  {
    id: "fried-kebbe-(5-pcs)",
    categorySlug: "mezze-calde",
    name: { ro: "Kebbe prăjite (5 bucăți)", en: "Fried Kebbe (5 pcs)" },
    description: { ro: "Carne tocată, grâu marinat, muguri de pin și ceapă", en: "Minced meat, marinated wheat, pine nuts and onion" },
    price: 49,
  },
  {
    id: "spicy-chicken-rolls-(3-pcs)",
    categorySlug: "mezze-calde",
    name: { ro: "Rulouri de pui picante (3 bucăți)", en: "Spicy Chicken Rolls (3 pcs)" },
    description: { ro: "Pui, ouă și ceapă", en: "Chicken, eggs and onion" },
    price: 44,
  },
  {
    id: "shrimp-rolls-(3-pcs)",
    categorySlug: "mezze-calde",
    name: { ro: "Rulouri cu creveți (3 bucăți)", en: "Shrimp Rolls (3 pcs)" },
    description: { ro: "Creveți, morcovi, ghimbir și vinete", en: "Shrimp, carrots, ginger and eggplant" },
    price: 50,
  },
  {
    id: "cheese-rolls-(4-pcs)",
    categorySlug: "mezze-calde",
    name: { ro: "Rulouri cu brânză (4 bucăți)", en: "Cheese Rolls (4 pcs)" },
    description: { ro: "Rulouri cu brânză și sos de roșii", en: "Rolls with cheese and tomato sauce" },
    price: 50,
  },
  {
    id: "sambusek-with-sujuk-(5-pcs)",
    categorySlug: "mezze-calde",
    name: { ro: "Sambusek cu sucuk (5 bucăți)", en: "Sambusek with Sujuk (5 pcs)" },
    description: { ro: "Aluat umplut cu sucuk", en: "Dough filled with spicy sausage" },
    price: 43,
  },
  {
    id: "assorted-pickles",
    categorySlug: "mezze-reci",
    name: { ro: "Murături asortate", en: "Assorted Pickles" },
    description: { ro: "Selecție de murături tradiționale", en: "Selection of traditional pickles" },
    price: 41,
  },
  {
    id: "telemea",
    categorySlug: "mezze-reci",
    name: { ro: "Telemea", en: "Feta Cheese" },
    description: { ro: "Brânză telemea proaspătă", en: "Fresh feta cheese" },
    price: 18,
  },
  {
    id: "makdous",
    categorySlug: "mezze-reci",
    name: { ro: "Makdous", en: "Makdous" },
    description: { ro: "Vinete umplute cu nuci, pastă de ardei și condimente", en: "Eggplant stuffed with walnuts, pepper paste and spices" },
    price: 46,
  },
  {
    id: "muhammara",
    categorySlug: "mezze-reci",
    name: { ro: "Muhammara", en: "Muhammara" },
    description: { ro: "Pastă de nuci cu ulei de măsline și boia", en: "Walnut paste with olive oil and paprika" },
    price: 49,
  },
  {
    id: "okra",
    categorySlug: "mezze-reci",
    name: { ro: "Bame", en: "Okra" },
    description: { ro: "Bame cu roșii, ceapă și condimente", en: "Okra with tomatoes, onions and spices" },
    price: 48,
  },
  {
    id: "moussaka",
    categorySlug: "mezze-reci",
    name: { ro: "Musaca", en: "Moussaka" },
    description: { ro: "Vinete cu roșii și condimente", en: "Eggplant with tomatoes and spices" },
    price: 49,
  },
  {
    id: "green-beans",
    categorySlug: "mezze-reci",
    name: { ro: "Fasole verde", en: "Green Beans" },
    description: { ro: "Fasole verde cu suc de roșii", en: "Green beans in tomato sauce" },
    price: 43,
  },
  {
    id: "lenten-sarmale",
    categorySlug: "mezze-reci",
    name: { ro: "Sarmale de post", en: "Lenten Stuffed Vine Leaves" },
    description: { ro: "Sarmale în foi de viță cu orez, roșii, ceapă și condimente", en: "Stuffed vine leaves with rice, tomatoes, onion and spices" },
    price: 41,
  },
  {
    id: "shanklish",
    categorySlug: "mezze-reci",
    name: { ro: "Shanklish", en: "Shanklish" },
    description: { ro: "Brânză condimentată cu cimbru, roșii, ceapă și pătrunjel", en: "Specialty cheese seasoned with thyme, tomatoes, onion and parsley" },
    price: 53,
  },
  {
    id: "labneh-zaitoone",
    categorySlug: "mezze-reci",
    name: { ro: "Labneh Zaitoone", en: "Labneh Zaitoone" },
    description: { ro: "Cremă proaspătă de iaurt cu măsline", en: "Fresh yogurt cream with olives" },
    price: 43,
    isSignature: true,
  },
  {
    id: "labneh-with-garlic-and-mint",
    categorySlug: "mezze-reci",
    name: { ro: "Labneh cu usturoi și mentă", en: "Labneh with Garlic and Mint" },
    description: { ro: "Cremă proaspătă de iaurt cu usturoi și mentă", en: "Fresh yogurt cream with garlic and mint" },
    price: 40,
  },
  {
    id: "labneh",
    categorySlug: "mezze-reci",
    name: { ro: "Labneh", en: "Labneh" },
    description: { ro: "Cremă proaspătă de iaurt", en: "Fresh yogurt cream" },
    price: 40,
  },
  {
    id: "baba-ganoush",
    categorySlug: "salate",
    name: { ro: "Baba Ganoush", en: "Baba Ganoush" },
    description: { ro: "Vinete coapte cu ceapă, usturoi, ardei, pătrunjel, lămâie și sos de rodie", en: "Baked eggplants with onion, garlic, bell pepper, parsley, lemon and pomegranate sauce" },
    price: 40,
    isSignature: true,
  },
  {
    id: "foul-mudamas",
    categorySlug: "mezze-reci",
    name: { ro: "Foul Mudamas", en: "Foul Mudamas" },
    description: { ro: "Fasole cu usturoi, lămâie, ulei de măsline și chimion", en: "Beans with garlic, lemon, olive oil and cumin" },
    price: 40,
  },
  {
    id: "balilla",
    categorySlug: "mezze-reci",
    name: { ro: "Balilla", en: "Balilla" },
    description: { ro: "Năut cu ulei de măsline și chimion", en: "Chickpeas with olive oil and cumin" },
    price: 40,
  },
  {
    id: "mudardara",
    categorySlug: "mezze-reci",
    name: { ro: "Mudardara", en: "Mudardara" },
    description: { ro: "Linte cu orez, ceapă și condimente", en: "Lentils with rice, onion and spices" },
    price: 40,
  },
  {
    id: "moutabal-with-truffles",
    categorySlug: "mezze-reci",
    name: { ro: "Moutabal cu trufe", en: "Moutabal with Truffles" },
    description: { ro: "Vinete coapte cu tahini, lămâie și trufe", en: "Baked eggplant with tahini, lemon and truffles" },
    price: 65,
  },
  {
    id: "moutabal",
    categorySlug: "mezze-reci",
    name: { ro: "Moutabal", en: "Moutabal" },
    description: { ro: "Vinete coapte cu tahini, lămâie și semințe de rodie", en: "Baked eggplant with tahini, lemon and pomegranate seeds" },
    price: 40,
  },
  {
    id: "hummus-with-shawarma",
    categorySlug: "mezze-reci",
    name: { ro: "Hummus cu shawarma", en: "Hummus with Shawarma" },
    description: { ro: "Pastă de năut cu tahini, lămâie și shawarma de vită", en: "Chickpea paste with tahini, lemon and beef shawarma" },
    price: 67,
  },
  {
    id: "hummus-with-extra-truffles",
    categorySlug: "mezze-reci",
    name: { ro: "Hummus cu trufe extra", en: "Hummus with Extra Truffles" },
    description: { ro: "Pastă de năut cu extra trufe, tahini, lămâie și ulei de măsline", en: "Chickpea paste with extra truffles, tahini, lemon and olive oil" },
    price: 82,
  },
  {
    id: "hummus-with-truffles",
    categorySlug: "mezze-reci",
    name: { ro: "Hummus cu trufe", en: "Hummus with Truffles" },
    description: { ro: "Pastă de năut cu trufe, tahini, lămâie și ulei de măsline", en: "Chickpea paste with truffles, tahini, lemon and olive oil" },
    price: 64,
  },
  {
    id: "pesto-hummus",
    categorySlug: "mezze-reci",
    name: { ro: "Hummus cu pesto", en: "Pesto Hummus" },
    description: { ro: "Pastă de năut cu tahini, lămâie, pesto și busuioc", en: "Chickpea paste with tahini, lemon, pesto and basil" },
    price: 53,
  },
  {
    id: "special-salad-(spicy)",
    categorySlug: "salate",
    name: { ro: "Salată specială (picantă)", en: "Special Salad (Spicy)" },
    description: { ro: "Focaccia, avocado, oregano, valeriană, ceapă, halloumi, ulei de măsline, sare, roșii și ardei iuți", en: "Focaccia, avocado, oregano, valerian, onion, halloumi, olive oil, salt, tomatoes and chili peppers" },
    price: 67,
  },
  {
    id: "coleslaw-salad",
    categorySlug: "salate",
    name: { ro: "Salată Coleslaw", en: "Coleslaw Salad" },
    description: { ro: "Varză, maioneză și morcov", en: "Cabbage, mayonnaise and carrot" },
    price: 33,
  },
  {
    id: "panache-salad-with-sauce",
    categorySlug: "salate",
    name: { ro: "Salată Panache cu dressing", en: "Panache Salad with Dressing" },
    description: { ro: "Avocado, salată verde, ciuperci, sparanghel și porumb", en: "Avocado, lettuce, mushrooms, asparagus and corn" },
    price: 50,
  },
  {
    id: "fresh-vegetable-platter",
    categorySlug: "salate",
    name: { ro: "Platou de legume proaspete", en: "Fresh Vegetable Platter" },
    description: { ro: "Selecție de legume proaspete", en: "Assorted fresh vegetables" },
    price: 77,
  },
  {
    id: "olive-salad-2",
    categorySlug: "salate",
    name: { ro: "Salată de măsline", en: "Olive Salad" },
    description: { ro: "Măsline verzi cu cimbru, nuci, ceapă, roșii, lămâie și pătrunjel", en: "Green olives with thyme, walnuts, onion, tomatoes, lemon and parsley" },
    price: 46,
  },
  {
    id: "olive-salad",
    categorySlug: "salate",
    name: { ro: "Salată Zaitoone", en: "Zaitoone Salad" },
    description: { ro: "Rucola, valeriană, oregano, măsline verzi, ceapă roșie, salată verde, roșii, sare, lămâie și ulei de măsline", en: "Arugula, valerian, oregano, green olives, red onion, lettuce, tomatoes, salt, lemon and olive oil" },
    price: 50,
  },
  {
    id: "grand-cru-elegance",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Shawarma de creveți", en: "Shrimp Shawarma" },
    description: { ro: "Creveți, tahini, chimion, coriandru, salată și cartofi prăjiți", en: "Shrimp, tahini, cumin, coriander, salad and fries" },
    price: 134,
  },
  {
    id: "citrus-burst-refresher",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Frigărui de creveți", en: "Shrimp Skewers" },
    description: { ro: "Creveți mari la grătar pe frigărui", en: "Large grilled shrimp on skewers" },
    price: 165,
  },
  {
    id: "midnight-velvet-martini",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Samkeh Harra", en: "Samkeh Harra" },
    description: { ro: "File de doradă cu sos tahini picant", en: "Sea bream fillet with spicy tahini sauce" },
    price: 93,
  },
  {
    id: "sparkling-elixir-royale",
    categorySlug: "peste-fructe-de-mare",
    name: { ro: "Doradă", en: "Sea Bream" },
    description: { ro: "Doradă cu piure de cartofi și sos picant cu ulei de măsline", en: "Sea bream with mashed potatoes and spicy olive oil sauce" },
    price: 154,
  },
  {
    id: "passion-soufflé-étoile",
    categorySlug: "gratar",
    name: { ro: "Mușchi de vită cu fistic și sparanghel", en: "Beef Tenderloin with Pistachios and Asparagus" },
    description: { ro: "Mușchi de vită, fistic, sos de muștar și sparanghel", en: "Beef tenderloin, pistachios, mustard sauce and asparagus" },
    price: 196,
  },
  {
    id: "lemon-tart-lumière",
    categorySlug: "gratar",
    name: { ro: "Mușchi de vită cu ciuperci", en: "Beef with Mushroom Sauce" },
    description: { ro: "Mușchi de vită cu sos de ciuperci și cartofi wedges", en: "Beef tenderloin with mushroom sauce and potato wedges" },
    price: 165,
  },
  {
    id: "pistachio-bliss-parfait",
    categorySlug: "gratar",
    name: { ro: "Beiti Kebab", en: "Beiti Kebab" },
    description: { ro: "Carne tocată cu ceapă, pătrunjel, condimente și cartofi prăjiți", en: "Minced meat with onion, parsley, spices and french fries" },
    price: 124,
  },
  {
    id: "chocolate-decadence-noir",
    categorySlug: "gratar",
    name: { ro: "Kafta cu tahini", en: "Kafta with Tahini" },
    description: { ro: "Carne tocată, pătrunjel, condimente, pastă de susan și cartofi prăjiți", en: "Minced meat, parsley, spices, sesame paste and french fries" },
    price: 118,
  },
  {
    id: "osso-buco-ambrosia",
    categorySlug: "carne-cruda",
    name: { ro: "Kebbeh Nayeh", en: "Kebbeh Nayeh" },
    description: { ro: "Carne crudă de miel cu grâu zdrobit și condimente speciale", en: "Raw lamb meat with crushed wheat and special spices" },
    price: 72,
    isSignature: true,
  },
  {
    id: "lobster-ravioli-divine",
    categorySlug: "carne-cruda",
    name: { ro: "Habra Nayeh", en: "Habra Nayeh" },
    description: { ro: "Pastă de vită crudă cu condimente speciale", en: "Raw beef paste with special spices" },
    price: 72,
  },
  {
    id: "burrata-cloud-caprese",
    categorySlug: "carne-cruda",
    name: { ro: "Kafta Nayeh", en: "Kafta Nayeh" },
    description: { ro: "Carne crudă tocată cu condimente libaneze tradiționale", en: "Raw minced meat with traditional Lebanese spices" },
    price: 72,
  },
  {
    id: "truffle-tagliatelle-dream",
    categorySlug: "carne-cruda",
    name: { ro: "Shi Kafta", en: "Shi Kafta" },
    description: { ro: "Variație de kafta crudă cu condimente orientale", en: "Raw kafta variation with oriental spices" },
    price: 72,
  },
  {
    id: "wagyu-tataki-umami",
    categorySlug: "mezze-calde",
    name: { ro: "Supă cremă de linte", en: "Lentil Cream Soup" },
    description: { ro: "Supă cremă de linte cu condimente orientale", en: "Creamy lentil soup with oriental spices" },
    price: 46,
    isSignature: true,
  },
  {
    id: "truffle-edamame-silk",
    categorySlug: "mezze-calde",
    name: { ro: "Sambusek cu carne (5 bucăți)", en: "Sambusek with Meat (5 pcs)" },
    description: { ro: "Aluat umplut cu carne tocată, ceapă și muguri de pin", en: "Dough filled with minced meat, onion and pine nuts" },
    price: 43,
  },
  {
    id: "king-crab-delight",
    categorySlug: "mezze-calde",
    name: { ro: "Sambusek cu brânză (5 bucăți)", en: "Sambusek with Cheese (5 pcs)" },
    description: { ro: "Aluat umplut cu brânză, ceapă, pătrunjel și mentă", en: "Dough filled with cheese, onion, parsley and mint" },
    price: 43,
  },
  {
    id: "toro-sashimi-azure",
    categorySlug: "mezze-calde",
    name: { ro: "Sambusek cu spanac (5 bucăți)", en: "Sambusek with Spinach (5 pcs)" },
    description: { ro: "Aluat umplut cu spanac, ceapă și rodie", en: "Dough filled with spinach, onion and pomegranate" },
    price: 43,
  },
  {
    id: "saffron-biryani-royale",
    categorySlug: "mezze-reci",
    name: { ro: "Hummus", en: "Hummus" },
    description: { ro: "Pastă de năut cu tahini și lămâie", en: "Chickpea paste with tahini and lemon" },
    price: 40,
  },
  {
    id: "tandoori-prawn-éclat",
    categorySlug: "mezze-reci",
    name: { ro: "Hummus Beiruti", en: "Beiruti Hummus" },
    description: { ro: "Pastă de năut cu tahini, lămâie, pătrunjel și ardei galben", en: "Chickpea paste with tahini, lemon, parsley and yellow pepper" },
    price: 40,
  },
  {
    id: "black-truffle-dal",
    categorySlug: "mezze-reci",
    name: { ro: "Hummus cu muguri de pin", en: "Hummus with Pine Nuts" },
    description: { ro: "Pastă de năut cu tahini, lămâie și muguri de pin", en: "Chickpea paste with tahini, lemon and pine nuts" },
    price: 49,
  },
  {
    id: "malai-kofta-velvet",
    categorySlug: "mezze-reci",
    name: { ro: "Hummus cu carne și muguri de pin", en: "Hummus with Meat and Pine Nuts" },
    description: { ro: "Pastă de năut cu tahini, lămâie, muguri de pin și carne de vită", en: "Chickpea paste with tahini, lemon, pine nuts and beef" },
    price: 59,
  },
  {
    id: "foie-gras-kiss",
    categorySlug: "salate",
    name: { ro: "Salată libaneză mixtă", en: "Mixed Lebanese Salad" },
    description: { ro: "Roșii, castraveți, salată verde, ceapă, ardei, ridichi, valeriană, mentă, lămâie și ulei de măsline", en: "Tomatoes, cucumbers, lettuce, onion, bell pepper, radishes, valerian, mint, lemon and olive oil" },
    price: 46,
  },
  {
    id: "caviar-pearls",
    categorySlug: "salate",
    name: { ro: "Salată arabească tocată fin", en: "Finely Chopped Arabian Salad" },
    description: { ro: "Roșii, castraveți, salată verde, ceapă, ardei, ridichi, mentă, lămâie și ulei de măsline", en: "Tomatoes, cucumbers, lettuce, onion, bell pepper, radishes, mint, lemon and olive oil" },
    price: 50,
  },
  {
    id: "lobster-whisper",
    categorySlug: "salate",
    name: { ro: "Tabbouleh", en: "Tabbouleh" },
    description: { ro: "Pătrunjel, ceapă, quinoa, lămâie și ulei de măsline", en: "Parsley, onion, quinoa, lemon and olive oil" },
    price: 49,
  },
  {
    id: "scallop-jewel",
    categorySlug: "salate",
    name: { ro: "Fattoush", en: "Fattoush" },
    description: { ro: "Castraveți, salată verde, ceapă, ardei, lămâie, ulei de măsline, valeriană, mentă și pâine prăjită", en: "Cucumbers, lettuce, onion, bell pepper, lemon, olive oil, valerian, mint and toast" },
    price: 55,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "andreea",
    name: "Andreea M.",
    role: { ro: "iubitoare de gastronomie", en: "food lover" },
    quote: { ro: "Arome autentice și o atmosferă caldă. Mezze-urile sunt spectaculoase!", en: "Authentic flavors and a warm atmosphere. The mezze is spectacular!" },
    rating: 5,
  },
  {
    id: "victor",
    name: "Victor P.",
    role: { ro: "corporate", en: "corporate" },
    quote: { ro: "Ideal pentru întâlniri de business: servicii discrete, preparate impecabile.", en: "Ideal for business meetings: discreet service, impeccable dishes." },
    rating: 5,
  },
  {
    id: "irina",
    name: "Irina C.",
    role: { ro: "ghid local", en: "local guide" },
    quote: { ro: "Ras Asfour și künefe sunt de neratat. Totul este 100% HALAL.", en: "Ras Asfour and kunefe are a must. Everything is 100% HALAL." },
    rating: 4,
  },
];

export const galleryImages = [
  {
    id: "hall",
    src: "/assets/Meals/meals-name/Cotlet Miel.png",
    alt: "Cotlet de miel",
  },
  {
    id: "table",
    src: "/assets/Meals/meals-name/Mix de fructe de mare la gratar cu salata ruccola.png",
    alt: "Fructe de mare la grătar",
  },
  {
    id: "bar",
    src: "/assets/Meals/meals-name/Fatteh Humus cu Carne si Muguri de Pin.png",
    alt: "Kibbeh",
  },
  {
    id: "garden",
    src: "/assets/Meals/meals-name/Baclawa cu inghetata.png",
    alt: "Baklava cu înghețată",
  },
  {
    id: "plate",
    src: "/assets/Meals/meals-name/Salata Zaitoone.png",
    alt: "Salată Zaitoone",
  },
  {
    id: "dessert",
    src: "/assets/Meals/meals-name/Beiti Kebab.png",
    alt: "Beiti Kebab",
  },
];

export const timeline = [
  {
    year: "2014",
    title: "The Taste of Liban – Since 2014",
    description: "Primul Zaitoone deschis în București, aducând mezze autentice.",
  },
  {
    year: "2017",
    title: "Bucharest North",
    description: "Extindere pe B-dul Nicolae Caramfil, aproape de business hub.",
  },
  {
    year: "2021",
    title: "Noua generație",
    description: "Meniu reimaginat, ingrediente premium și vinuri selecționate.",
  },
  {
    year: "2024",
    title: "Experiențe private",
    description: "Evenimente corporate și seri romantice personalizate.",
  },
];

export const eventPackages = [
  {
    title: "Private Dining",
    description: "Salon elegant pentru grupuri restrânse, meniuri degustare.",
    cta: "Planifică o seară",
  },
  {
    title: "Corporate Events",
    description: "Business dinners, chef’s table, vinuri pairing cu somelier.",
    cta: "Solicită ofertă",
  },
  {
    title: "Celebrations",
    description: "Aniversări, logodne, seri tematice cu muzică live.",
    cta: "Rezervă momentul",
  },
];

export const highlightCards = [
  {
    title: "Tradiție libaneză autentică",
    description: "Rețete moștenite, reinterpretate elegant pentru București.",
  },
  {
    title: "Ingrediente premium",
    description: "Ulei de măsline din Valea Bekaa, condimente proaspăt prăjite.",
  },
  {
    title: "Atmosferă caldă",
    description: "Lumini joase, muzică discretă, ospitalitate libaneză.",
  },
];

export const location = {
  address: "B-dul Nicolae Caramfil 2, București",
  hours: [
    "Luni - Duminică: 12:00 - 00:00",
  ],
  phone: "+40 731 000 000",
  email: "rezervari@zaitoone.ro",
};

